### ISSUE TITLE
插入模式下tab键失效

### ISSUE THREAD

**Issue by ACautomata** [GavinSun0921/Auto-configuration-vim#1]
错误提示：
E117: Unknown Function<SNR>check_back_space

**Comment by ACautomata** [comment]
解决方案：https://stackoverflow.com/questions/74158726/vimscript-calling-function-inside-inoremap-throws-unknown-function

**Comment by GavinSun0921** [comment]
貌似是自动补全插件的bug，感谢提供解决方案
